name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master # master 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master # 使用专门部署 Hexo 到 GitHub pages 的 action
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }} # secret 名
          PUBLISH_REPOSITORY: zyhwjl2022/zyhwjl2022.github.io # 公共仓库，格式：GitHub 用户名/仓库名
          BRANCH: gh-pages # 分支，填 gh-pages 就行
          PUBLISH_DIR: ./public # 部署 public 目录下的文件
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Sync to Gitee
  #       uses: wearerequired/git-mirror-action@master
  #       env:
  #         # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
  #         SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
  #       with:
  #         # 注意替换为你的 GitHub 源仓库地址
  #         source-repo: git@github.com:zyhwjl2022/HexoBlogSource.git
  #         # 注意替换为你的 Gitee 目标仓库地址
  #         destination-repo: git@gitee.com:zyhwjl/blog-source.git
